import { test, expect } from '@playwright/test';
import type { Page } from '@playwright/test';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));

// env.json is generated by test/e2e-live/setup.mjs before the run
const env = JSON.parse(
  fs.readFileSync(path.join(here, 'env.json'), 'utf8'),
) as {
  serverUrl: string;
  clientKey: string;
  serverKey: string;
  flags: { full: string; off: string; anon66: string; user32: string };
};

const FIXTURE = '/test/e2e/fixtures/fixture.html';

function fixtureUrl(opts: { key?: string; mode?: string; anonId?: string; sticky?: boolean }): string {
  const params = new URLSearchParams({ url: env.serverUrl });
  if (opts.key) params.set('key', opts.key);
  if (opts.mode) params.set('mode', opts.mode);
  if (opts.anonId) params.set('anonId', opts.anonId);
  if (opts.sticky === false) params.set('sticky', 'false');
  return `${FIXTURE}?${params.toString()}`;
}

function captureEvaluateBody(page: Page): () => string | null {
  let body: string | null = null;
  page.on('request', (req) => {
    if (req.method() === 'POST' && req.url().includes('/api/client/evaluate')) {
      body = req.postData();
    }
  });
  return () => body;
}

test.describe('live server (client mode)', () => {
  test('anonymousId is sent and real server toggles are applied', async ({ page }) => {
    const getBody = captureEvaluateBody(page);
    await page.goto(fixtureUrl({ key: env.clientKey, mode: 'client', anonId: 'anon-1' }));
    await page.waitForFunction(() => window.__mozhno.ready);

    // deterministic bucket: tf-anon + anon-1 -> 99, 99 < 66 => false
    const r = await page.evaluate((flags) => ({
      full: window.__mozhno.client.isEnabled(flags.full),
      off: window.__mozhno.client.isEnabled(flags.off),
      anon: window.__mozhno.client.isEnabled(flags.anon66),
    }), env.flags);

    expect(r.full).toBe(true);  // 100%
    expect(r.off).toBe(false);  // 0%
    expect(r.anon).toBe(false); // 66% with bucket 99

    const body = JSON.parse(getBody()!);
    expect(body.context.anonymousId).toBe('anon-1');
    expect(await page.evaluate(() => localStorage.getItem('mozhno_anon_id'))).toBe('anon-1');
  });

  test('reload: sticky results against the real server', async ({ page }) => {
    await page.goto(fixtureUrl({ key: env.clientKey, mode: 'client', anonId: 'anon-1' }));
    await page.waitForFunction(() => window.__mozhno.ready);
    const r1 = await page.evaluate((key) => window.__mozhno.client.isEnabled(key), env.flags.anon66);

    await page.reload();
    await page.waitForFunction(() => window.__mozhno.ready);
    const r2 = await page.evaluate((key) => window.__mozhno.client.isEnabled(key), env.flags.anon66);

    expect(r2).toBe(r1);
    expect(await page.evaluate(() => localStorage.getItem('mozhno_anon_id'))).toBe('anon-1');
  });

  test('stickyAnonId=false: anonymousId is not sent, warn is logged', async ({ page }) => {
    const getBody = captureEvaluateBody(page);
    const warnings: string[] = [];
    page.on('console', (m) => {
      const text = m.text();
      if (text.includes('stickyAnonId')) warnings.push(text);
    });

    await page.goto(fixtureUrl({ key: env.clientKey, mode: 'client', sticky: false }));
    await page.waitForFunction(() => window.__mozhno.ready);
    await page.evaluate((key) => window.__mozhno.client.isEnabled(key), env.flags.full);

    expect(JSON.parse(getBody()!).context.anonymousId).toBeUndefined();
    expect(await page.evaluate(() => localStorage.getItem('mozhno_anon_id'))).toBeNull();
    expect(warnings.join('\n')).toContain('stickyAnonId');
  });
});

test.describe('live server (server mode)', () => {
  test('real /api/client/features payload is parsed and evaluated with spec buckets', async ({ page }) => {
    await page.goto(fixtureUrl({ key: env.serverKey, mode: 'server' }));
    await page.waitForFunction(() => window.__mozhno.ready);

    const r = await page.evaluate((flags) => ({
      full: window.__mozhno.client.isEnabled(flags.full),
      off: window.__mozhno.client.isEnabled(flags.off),
      user1: window.__mozhno.client.isEnabled(flags.user32, { userId: 'user-1' }),
      anon1: window.__mozhno.client.isEnabled(flags.anon66, { anonymousId: 'anon-1' }),
    }), env.flags);

    expect(r.full).toBe(true);
    expect(r.off).toBe(false);
    // tf-user + user-1 -> bucket 31, 31 < 32 => true
    expect(r.user1).toBe(true);
    // tf-anon + anon-1 -> bucket 99, 99 < 66 => false
    expect(r.anon1).toBe(false);
  });

  test('ready and update events fire', async ({ page }) => {
    await page.goto(fixtureUrl({ key: env.serverKey, mode: 'server' }));
    await page.waitForFunction(() => window.__mozhno.ready);

    const log = await page.evaluate(() => window.__mozhno.log.join('\n'));
    expect(log).toContain('[ready]');
    expect(log).toContain('[update]');
  });

  test('real server returns ETag and honors If-None-Match (304)', async ({ page }) => {
    await page.goto(fixtureUrl({ key: env.serverKey, mode: 'server' }));
    await page.waitForFunction(() => window.__mozhno.ready);

    const result = await page.evaluate(async ({ url, key }) => {
      const headers = { Authorization: `Bearer ${key}`, 'X-Mozhno-App-Name': 'e2e' };
      const first = await fetch(url + '/api/client/features', { headers });
      const etag = first.headers.get('ETag');
      const second = await fetch(url + '/api/client/features', {
        headers: { ...headers, 'If-None-Match': etag! },
      });
      return { firstStatus: first.status, etag, secondStatus: second.status };
    }, { url: env.serverUrl, key: env.serverKey });

    expect(result.firstStatus).toBe(200);
    expect(result.etag).toBeTruthy();
    expect(result.secondStatus).toBe(304);
  });

  test('server evaluate matches local evaluation (parity)', async ({ page }) => {
    await page.goto(fixtureUrl({ key: env.serverKey, mode: 'server' }));
    await page.waitForFunction(() => window.__mozhno.ready);

    const r = await page.evaluate(async ({ url, clientKey, flags }) => {
      const evaluate = async (context: Record<string, string>) => {
        const res = await fetch(url + '/api/client/evaluate', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${clientKey}`,
            'Content-Type': 'application/json',
            'X-Mozhno-App-Name': 'e2e',
          },
          body: JSON.stringify({ context }),
        });
        const data = await res.json();
        const map: Record<string, boolean> = {};
        for (const t of data.toggles || []) map[t.name] = t.enabled;
        return map;
      };

      const server = await evaluate({ userId: 'user-1' });
      return {
        // full-flag: 100% => true на сервере и локально
        serverFull: server[flags.full] ?? false,
        localFull: window.__mozhno.client.isEnabled(flags.full),
        // tf-user + user-1: bucket 31 < 32 => true везде
        serverUser32: server[flags.user32] ?? false,
        localUser32: window.__mozhno.client.isEnabled(flags.user32, { userId: 'user-1' }),
      };
    }, { url: env.serverUrl, clientKey: env.clientKey, flags: env.flags });

    expect(r.serverFull).toBe(r.localFull);
    expect(r.serverUser32).toBe(r.localUser32);
  });
});
